Alex-Laney/JuniorDesign2329

lib/main.dart

There is now a third screen in the rotation and each of the module screens has two buttons, the top sends to next and the bottom sends to previous

Third Screen and double buttons

---

README.md
lib/Composers/Composers.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Works/Musical-Works.dart
lib/Quizzes/Quizzes.dart
lib/main.dart
pubspec.lock
pubspec.yaml

- Recreated GUI from Pull Request "#18" for all other screens aside from the Home Screen
- Added 'Return Home' functionality to the 'Home Button' on the menu bar
- Functionality from one module given to the others
- The button corresponding to the module you are currently looking at is present on the selector, and will simply send you to that module again. This is far from final functionality, and will need to be revised and removed.

Expanded Module Selector

---

lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart

Terms database added with 10 terms

Add terms database with 10 terms

---

lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart

Update from Main

---

lib/Musical-Terms/Definition-Page.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Terms/Term.dart

Added functionality and basic interface to the Terms page. It now pulls from the terms database to generate and display a list of terms. A dropdown menu is in place to support sorting.
EDIT: Now includes definition pages
Current state of term menu screen
Current state of term menu screen, with dropdown selected.
EDIT: Now includes implemented definitions page
Still missing integration of sort functionality, as well as UI styling, awaiting supporting work. These will both be implemented when ready.
Unsure how it functions with scrolling. It should work, but if this becomes an issue as more terms are added, I will fix it.

Implement Musical Terms Menu

---

lib/Composers/Composers.dart
lib/Musical-Terms/Definition-Page.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Works/Musical-Works.dart
lib/Quizzes/Quizzes.dart
lib/main.dart
lib/settings/settings_menu.dart
pubspec.lock

- Added a basic settings screen
- Has changes from #25, so that PR should be dealt with first before this one

Settings Screen

---

lib/main.dart
lib/settings/about_screen.dart
lib/settings/help_menu.dart

- Added licensing agreements and disclaimer in the about screen
- Added backbone for the upcoming help menu
- Decided to put the licensing things in the about page, but feel free to leave suggestions on where it should be put
- Edit: Going light on the styling of things since I believe we are working on that
- Edit: about page is a work in progress
- Edit: Right now the license page is kind of slow to load. Not sure if that is fixable or not.

Licensing Screen

---

lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart

Added ability to group terms by their tag.
- Non-Functional Change (non-user facing changes)
Only works for a single tag

Added ability to group terms by tag

---

lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart

The Terms list is now sorted appropriately when the preferred sorting type is selected.
Pull #29 first, since it implements the sorting function that is used here.
If other sorting types (alphabetical, reverse alphabetical, etc.) are implemented, this step can be done trivially.

Tag sorting UI update

---

pubspec.yaml

Fixes pubspec.yaml dependency error with main
I know this was pushed from "master" branch which is confusing, but this is from a  branch that is NOT our main. This is an issue with my local repo, my bad!

Fixes pubspec asset dependency error

---

lib/Composers/Composers.dart
lib/Listen/Listen.dart
lib/Musical-Terms/Definition-Page.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Terms/Term.dart
lib/Musical-Works/Musical-Works.dart
lib/Quizzes/Quizzes.dart
lib/main.dart
lib/settings/about_screen.dart
lib/settings/help_menu.dart
lib/settings/help_menus/composers_help.dart
lib/settings/help_menus/music_help.dart
lib/settings/help_menus/musical_terms_help.dart
lib/settings/help_menus/quizzes_help.dart
lib/settings/settings_menu.dart
pubspec.lock

- Added background color that match to the Figma design
- Might refactor to a single variable for each color

Background color to Modules

---

android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
lib/Musical-Terms/Musical-Terms.dart
pubspec.lock

Sort for Reverse Alphabetical now works
Currently, sorting by tags sorts alphabetically then by tags, so the tag sort is consistent regardless of previous list state.

Implements UI portion of Reverse Alphabetical Sort

---

lib/Linkable Interface/linkable.dart
lib/Linkable Interface/none_linkable.dart
lib/Musical-Terms/Definition-Page.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart

Creates the Linkable interface, to be implemented by anything we wish to be linked to within text (Composers, Works, Terms, etc.). Also created a NoneLinkable type to support text with no link associated. Used these changes to simplify existing code.
- Non-Functional Change (non-user facing changes)
I also fixed some compiler errors I may have created when resolving conflicts from a previous merge. My bad.

Implement Linkable Interface

---

lib/Musical-Works/Composition-Page.dart
lib/Musical-Works/Composition.dart
lib/Musical-Works/CompositionsDB.dart

The full integration of the Linkable interface in the code for the Musical Works module is included in this pull request.
Effectively, text that is included in this module can link to the Terms module, creating the most involved connection between modules developed for the app thus far.
- Non-Functional Change (non-user facing changes)

Implementing Linkable Interface in Musical Works Module

---

.vscode/settings.json
lib/Composers/Beethoven.dart
lib/Listen/Listen.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Terms/Term.dart
lib/Musical-Works/Composition-Page.dart
lib/Musical-Works/Composition.dart
lib/Musical-Works/Musical-Compositions.dart
lib/Quizzes/Quizzes.dart
lib/main.dart
pubspec.lock

This resolves [OM2329-50](https://jib-2329.atlassian.net/browse/OM2329-50) by implementing a universal button style in Main.dart. Since there is now one universal style, this branch also removes the individual button styles of other classes.
Because of this global style, it has edited the font for the Terms page. This style will need to be individually and manually overwritten.

Global ButtonStyle implementation

---

lib/Musical-Works/Composition-Page.dart
lib/Musical-Works/CompositionsDB.dart

Added information for the four present compositions
The four present compositions in the application at the moment (Fur Elise, Sonata 1, Sonata 8 and Moonlight Sonata) all have descriptions and comparisons to other genres, utilizing links to terms

Composition Text

---

lib/settings/help_menus/musical_terms_help.dart

Exactly as the title describes.
Also included icon and text color change inline where appropriate, to avoid a large unreadable block of text.

Adds content to the Musical Terms Help Page

---

lib/settings/help_menus/composers_help.dart

Added help screen to explain the composers module
- Non-Functional Change (non-user facing changes)
- Breaking change (fix or feature that would cause existing functionality to change)

Added help screen for composers module

---

android/app/build.gradle
lib/Quizzes/QuestionSemantics/question_screen.dart
lib/Quizzes/QuestionSemantics/quiz_question.dart
lib/Quizzes/Quizzes.dart
lib/Quizzes/Quizzes/quizDB.dart
lib/Quizzes/Quizzes/quiz_questionsDB.dart
lib/Quizzes/Results.dart
lib/main.dart
pubspec.lock

Added results screen to quizzes

Quiz results

---

lib/music_box.dart
lib/settings/settings_menu.dart
pubspec.lock

Fixes mute not working with the global player
-

Fix to make mute work for global music player

---

lib/Composers/Bach.dart
lib/Composers/Beethoven.dart
lib/Composers/Composers.dart
lib/Composers/Mozart.dart
lib/Listen/Listen.dart
lib/Musical-Terms/Definition-Page.dart
lib/Musical-Terms/Musical-Terms.dart
lib/Musical-Works/Composition-Page.dart
lib/Musical-Works/Musical-Compositions.dart
lib/Musical-Works/Musical-Works-Old.dart
lib/Quizzes/Quizzes.dart
lib/Quizzes/Results.dart
lib/Quizzes/quiz.dart
lib/Quizzes/start_screen.dart
lib/bottom_button_bar.dart
lib/bottom_navigation_bar/bottom_button_bar.dart
lib/bottom_navigation_bar/circular_dial_menu.dart
lib/hive_local_data/quiz_result/quiz_result_db.dart
lib/hive_local_data/rewards/rewards_points_db.dart
lib/main.dart
lib/rewards/rewards_screen.dart
lib/settings/about_screen.dart
lib/settings/help_menu.dart
lib/settings/help_menus/composers_help.dart
lib/settings/help_menus/musical_terms_help.dart
lib/settings/help_menus/quizzes_help.dart
lib/settings/help_menus/works_help.dart
lib/settings/settings_menu.dart
pubspec.lock

- Added rewards screen
- Added functionality to go to rewards module from the quizzes module
- Resolves [OM2329-74](https://jib-2329.atlassian.net/browse/OM2329-74)
- I'm not entirely sure how we plan to structure the rewards module, so I left the rewards module as a blank screen. 
- This PR contains changes from #66

Add Rewards Screen

---

lib/Quizzes/QuestionSemantics/question_screen.dart
lib/Quizzes/Quizzes/quizDB.dart
lib/Quizzes/Quizzes/quiz_questionsDB.dart
lib/Quizzes/Results.dart
lib/Quizzes/quiz.dart
lib/hive_local_data/quiz_result/quiz_result_db.dart
pubspec.lock

Adds the ability to track high scores and gain reward points (1 for each question correct, based on highest score). Additionally, the displays were fixed so that "ScorePlaceholder" is replaced with a score value color-coded based on percentage correct, and the results screen now displays how many points were earned by this quiz attempt.
Also fixed bug where users could use system back gestures on screens they should not have been able to
Fixed quiz names to be readable strings rather than non-spaced variable names
Changed the wording of one quiz question to make sense as True/False as opposed to Yes/No
The choice to not include a leaderboard was made since asking the user to …

High Score Tracking

---

lib/Quizzes/Results.dart
pubspec.lock

When I implemented High Score tracking, I forgot that there was a separate task for reward point tracking, and implemented that as well. Since this caused reward points to be earned twice, I have removed my implementation.

Fixed issue where Reward points were doubled

---

lib/Composers/Composers.dart
lib/Musical-Terms/Term.dart
lib/Musical-Terms/TermsDB.dart
lib/hive_local_data/rewards/rewards_points_db.dart

Fixed various issues: Mainly text overflow in Composers title, Reward points not updating upon taking a quiz after spending reward points.

General Bug Fixes

---

lib/Quizzes/QuestionSemantics/question_screen.dart
lib/hive_local_data/rewards/rewards_points_db.dart
lib/settings/settings_menu.dart

- Fixed bufferoverflow with quiz questions

Fix quiz question `bufferoverflow`
